language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install -r requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements-2.txt; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pylint rest_easy --rcfile=.pylintrc3; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pylint rest_easy --rcfile=.pylintrc; fi
  - coverage run --source=rest_easy -m rest_easy.runtests
